const express = require('express')
var cors = require('cors')
const connection = require('./connection')
const userRoute = require('./backend/routes/user')
const subjectRoute = require('./backend/routes/subjects')
const teacherRoute = require('./backend/routes/teachers')
const billRoute = require('./backend/routes/bill')
const dashboardRoute = require('./backend/routes/dashboard')
const app = express()

app.use(cors())
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use('/user',userRoute)
app.use('/subjects',subjectRoute)
app.use('/teachers',teacherRoute)
app.use('/bill',billRoute)
app.use('/dashboard',dashboardRoute)

module.exports = app